### Set up notebook

In [1]:
import os
os.chdir('../')
os.getcwd()

'/Users/Cisco/Desktop/Master_Dauphine/M2_IEF/cours/semestre2/MachineLearning/projet'

### Import raw data

In [2]:
import pandas as pd

In [8]:
data = pd.read_csv('data/cac40_v3.csv').drop('Unnamed: 0', axis=1)
data

,TICKER,annee,mois,jour,OP,UP,DO,CL,VO,RDMT_J,...,strategique,transaction,actionnaires,coentreprise,construction,collaboration,developpement,l_acquisition,participation,recommandation
0,AC,2007,10,1,50.820,52.450,50.720,52.440,939518,0.045576,...,0,0,0,0,0,0,0,0,0,0
1,AC,2007,10,10,57.600,57.900,56.480,56.740,1167710,0.005640,...,0,0,0,0,0,0,0,0,0,0
2,AC,2007,10,11,56.570,57.900,56.570,57.060,910369,-0.005258,...,0,0,0,0,0,0,0,0,0,0
3,AC,2007,10,12,57.100,57.100,55.500,56.760,996349,-0.011628,...,0,0,0,0,0,0,0,0,0,0
4,AC,2007,10,15,56.760,57.290,55.770,56.100,573647,-0.003209,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106537,VIV,2017,9,4,20.065,20.235,20.030,20.100,2250835,0.002736,...,0,0,0,0,0,0,0,0,0,0
106538,VIV,2017,9,5,20.095,20.290,19.985,20.155,3095238,-0.001985,...,0,0,0,0,0,0,0,0,0,0
106539,VIV,2017,9,6,20.080,20.210,20.015,20.115,2181925,-0.006463,...,0,0,0,0,0,0,0,0,0,0
106540,VIV,2017,9,7,20.185,20.185,19.920,19.985,4038684,-0.002252,...,0,0,0,0,0,0,0,0,0,0
106541,VIV,2017,9,8,19.865,20.025,19.820,19.940,1933282,0.024072,...,0,0,0,0,0,0,0,0,0,0

### Question 1)

Donner les charactéristiques de la base :
- Nombre de lignes
- Nombre de colonnes
- Format / Type de colonnes

In [6]:
print(f"Nombre de lignes : {data.shape[0]}")
print(f"Nombre de colonees : {data.shape[1]}")

Nombre de lignes : 106542
Nombre de colonees : 280

In [ ]:
for series_name, series in data.iteritems():
    print(f"Colonne : {series_name}, Type : {series.dtype}")

### Question 2)

Présenter quelques statistiques de la base

In [ ]:
data.describe()

### Question 3)

Montrer que, _quelque soit le ticker_, la liste des mots apparaissant sur 400 lignes et dont le rendement mensuel est en moyenne supérieur à 1% est telle que la table dans le sujet.

In [11]:
import numpy as np

word_flag = "avec"
ix_word_flag = np.argmax(data.columns == word_flag)
all_words = data.columns[ix_word_flag:]
not_words = data.columns[:ix_word_flag]

In [46]:
# On veut l'effet du mot, indépendamment de ticker
freq_word_ret = {}
for word in all_words:
    if data[word].sum() > 400:
        mean_return = np.mean(data["RDMT_M"].loc[data[word] == 1])
        if mean_return > 0.01:
            freq_word_ret[word] = mean_return

In [47]:
freq_word_ret

{'part': 0.011925091555993018,
 'plus': 0.010119257588012652,
 'pour': 0.013645055868837895,
 'euros': 0.010361023597468611,
 'group': 0.012940358066579583,
 'passe': 0.01376329128793489,
 'titre': 0.012178265842055443,
 'groupe': 0.014646081429147735,
 'nouvel': 0.011500023035921798,
 'releve': 0.010296593113268828,
 'actions': 0.01016788292303123,
 'capital': 0.011974752777913301,
 'contrat': 0.01057704828737451,
 'nouveau': 0.011895224332522554,
 'capital.': 0.011040725408502755,
 'nouvelle': 0.011975116627910317,
 'objectif': 0.014702096122149608,
 'resultat': 0.011162225879723832}

<b>Filtrer la base sur l'apparition de ces mots</b>